spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  kafka.bootstrap-servers: localhost:9092
  main:
    allow-bean-definition-overriding: true
camunda:
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest
      worker-id: spring-boot-worker
      basic-auth:
        username: demo
        password: demo
      disable-backoff-strategy: true
      async-response-timeout: 3000
server:
  port: 8090
logging:
  level:
    org.camunda.bpm.client: debug